development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: test
  username: root
  password: "12345"
  reconnect: true

production:
  adapter: mysql
  encoding: utf8
  host: localhost
  database: 
  username: 
  password: 
  reconnect: 